wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    code_path: code/examples/snnax_train_dvsgesture_multiloss_debug.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1670627111
    t:
      1:
      - 12
      - 55
      2:
      - 1
      - 12
      - 41
      - 55
      4: 3.8.10
      5: 0.12.15
      8:
      - 2
      - 5
act_rate:
  desc: null
  value: 0.3
alpha:
  desc: null
  value: 0.95
beta:
  desc: null
  value: 0.85
burnin:
  desc: null
  value: 100
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.009537878712151728
ro_int:
  desc: null
  value: 20
size_factor:
  desc: null
  value: 3

